#!/usr/bin/env bash
# install nginx in my server.
sudo apt-get update -y -qq && \
	sudo apt-get -y install nginx

sudo service nginx start
sudo utf allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod +R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" | dd status=none of=/var/www/html/index.ngins-debian.html

sudo service nginx restart
