#!/usr/bin/env bash
# install nginx in my server.

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo sh -c 'echo "Hello World!" > /var/www/html/index.ngins-debian.html'
sudo service nginx start
