#!/usr/bin/env bash
# install nginx in my server, redirect 301 from old page to
# youtube

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo sed -i '24i\    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
sudo sh -c 'echo "Hello World!" > /var/www/html/index.ngins-debian.html'

sudo service nginx start
sudo nginx -s reload
