#!/usr/bin/env bash
# install nginx in my server, redirect 404

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
#echo "Ceci n'est pas une page\n" >> /var/www/html/404.html'
sudo sh -c 'echo "Ceci n'\''est pas une page\n" > /var/www/html/404.html'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.ngins-debian.html'
sudo sed -i '22i\    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
sudo sed -i '12i\	error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload

