#!/usr/bin/env bash
#install nginx and HTTP header must X-Servved-By, host name o server nginx is running on.

temp=$(hostname)

new_1="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.youtube.com;"
new_2="server {\n\tadd_header X-Served-By $temp;"
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_1/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_2/" /etc/nginx/sites-available/default

sudo service nginx start
