#!/usr/bin/env bash
#install nginx and HTTP header must X-Servved-By, host name o server nginx is running on.

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo sh -c "echo \"add_header X-Served-By $hostname\" >> /etc/nginx/nginx.conf"
sudo service nginx start
