#!/usr/bin/env bash
# installing haproxy and create a traffic for you servers
# Distribute requests using a reoundrobin algorithm
# is HAproxy managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sh -c 'echo "frontend haproxy_balancer
    mode http
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    mode http
    server 26071-web-01 35.174.209.24:80
    server 26071-web-02 52.91.123.88:80
" > /etc/haproxy/haproxy.cfg'

sudo systemctl restart haproxy
