#!/usr/bin/env bash
#Write a Bash script that pings an IP address passed as an argument.

issues(){
	echo "Usage: $0 {IP_ADDRESS}"
}

if [ "$0" -eq 0 ]; then
	issues
	exit 1
fi
IP_ADDRESS=$1
ping -c 5 "$IP_ADDRESS"
