#!/usr/bin/env bash
#Write a Bash script that pings an IP address passed as an argument.

IP_AD=${1}
filename=$(basename "${BASH_SOURCE[0]}")
if ! [ "$IP_AD" ]; then
	echo "Usage: ${filename} {IP_ADDRESS}"
else
	ping -c 5 "$IP_AD"
fi
