#!/usr/bin/env bash
# magic lines to solve the issue in container ...
# this bash script is to solve the issue in the container

sudo apt update
sudo apt install -y nginx
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx restart

