#!/usr/bin/env bash
# magic lines to solve the issue in container ...
# this bash script is to solve the issue in the container

sudo apt update
sudo apt install -y nginx
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;' /etc/nginx/sites-available/default
sudo service nginx restart

