#!/usr/bin/env bash
# magic lines to solve the issue in container ...
# this bash script is to solve the issue in the container

sudo apt update
sudo apt install -y nginx

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

