#!/usr/bin/env bash
# disp bad after 4th l
# disp good luck after 8th l
# bast schools itarations!?

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
((i++))
done