#!/usr/bin/env bash

# display hours from 0 to 12
# display minutes from 1 to 59

j=0
i=1
while [ "$j" -le 12 ]; do
    echo "Hour: $j"
    while [ "$i" -lt 60 ]; do
        echo "$i"
        i=$((i+1))
    done

    j=$((j+1))
    i=1
done
