#!/usr/bin/env bash

# display hours from 0 to 12
# display minutes from 1 to 59

j=0
i=1
while [ "$j" -le 12 ]; do
    echo "Hour: $j"
    while [ "$i" -le 59 ]; do
        echo "$i"
        ((i++))
    done
    i=1
    ((j++))
done
