#!/usr/bin/env bash

# display hours from 0 to 12
# display minutes from 1 to 59

j=0
i=1
echo "Hour: 0"
while [ $j -lt 59 ]
do
    echo $j
    ((j++))
done
echo "Hour: 1"
while [ $i -lt 12 ]
do
    echo $i
    ((i++))
done
