#!/usr/bin/env bash
# this script test if the file is exist or not.


school="school"
if [ -e "$school" ]; then
    echo "school file exists"

    if [ -s "$school" ]; then
        echo "school file does not exist"
    else
        echo "school file is empty"
    fi

    if [ -f "$school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
