#!/usr/bin/env bash
# configure nginx to serve /airbnb_onepage


printf "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /airbnb-onepage {
        alias /data/web_static/current;
        index index.html index.htm;
    }

    location /airbnb-onepage {
        proxy_pass http://localhost:5000/airbnb-onepage;
    }

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > | sudo tee /etc/nginx/sites-available/default >/dev/null
sudo systemctl restart nginx
