#!/usr/bin/env bash
# configure nginx to serve /airbnb_onepage


printf "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    server_name 54.237.12.175;

    location = /airbnb-onepage/ {
        proxy_pass http://localhost:5000/airbnb-onepage/;
    }

    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/\$1;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:5002/api/;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > | sudo tee /etc/nginx/sites-available/default >/dev/null
sudo systemctl restart nginx

